# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: windows_x64_test
  pool:
    vmImage: windows-latest

  steps:
  - script: git submodule update --init vcpkg
    displayName: Initialise vcpkg submodule
    
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      md build
      cd build
      cmake -G Ninja -DSK_ERROR_BUILD_TESTS:BOOL=ON ..
    displayName: CMake

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      cd build
      ninja -v
    displayName: Build

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      cd build
      ctest -V 
    displayName: CTest
